name: Einsatzmonitor JPEG Erstellung

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

permissions:
  contents: write

jobs:
  screenshot:
    name: Google Tabelle als JPEG
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Screenshot erstellen
        run: node screenshot.js

      - name: JPEG speichern
        uses: EndBug/add-and-commit@v9
        with:
          add: einsatzplan.jpeg
          message: "Automatische Aktualisierung Einsatzmonitor"
